title:          "Unofficial GitHub Buttons"
description:    "A set of static buttons with dynamic watch and fork counts for any repo hosted on GitHub."
url:            "https://ghbtns.com"

# Social
authors:        "Mark Otto"
author:
  twitter:      "mdo"

permalink:      pretty

exclude:
- ".sass-cache"
- "Gemfile"
- "Gemfile.lock"
- "html-minifier.json"
- "LICENSE.md"
- "package.json"
- "package-lock.json"
- "README.md"
- "node_modules/"
- "src/"

sass:
  style: compressed

plugins:
  - jekyll-seo-tag
